config/routes.rb
Rails.application.routes.draw do

  root :to => 'questions#index'

  resources :users
  resources :sessions
  resources :questions do
    resources :answers
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  validates :text, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :title, :presence => true
  validates :content, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :questions
  has_many :answers
  validates :name, :presence => true
  validates :email, :presence => true
  after_create :send_signup_confirmation

def send_signup_confirmation
    UserMailer.signup_confirmation(self).deliver_now
  end

end

app/controllers/answers_controller.rb
class AnswersController <  ApplicationController
before_filter :authorize, only: [:create, :edit, :update, :delete]
  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
	  @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id
    @answer.question_id = @question.id
	  if @answer.save
	    flash[:notice] = "Answer added!!"
	    redirect_to question_path(@question)
	  else
	    render :new
	  end
	end


	def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to question_path(@question, @answer)
    else
      render :edit
    end
  end

   def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end

  private
  def answer_params
    params.require(:answer).permit(:text, :user_id, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/questions_controller.rb
class QuestionsController <  ApplicationController
before_filter :authorize, only: [:create, :edit, :update, :delete]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])


  end

  def edit
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      flash[:notice] = "Question saved"
      redirect_to questions_path
    else
      render :new
  end
end


  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
     redirect_to @question, notice: "Question has been updated"
   else
     render :edit
   end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end
private
def question_params
  params.require(:question).permit(:title, :content, :user_id)
end
end

app/controllers/sessions_controller.rb
class SessionsController <  ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "logged in!"
    else
      flash.now.alert ="Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController <  ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "thanks for signing up"
    else
      render :new
    end
  end

  def index
    @users = User.all
    render:show
  end

  def show
    @users = User.all
  end
private
def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>

<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/answers/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
    <div class="col-md-6 center-form">
      <h4>Answer this question!</h4>
    <%= form_for [@question, @answer] do |f| %>
      <% if @answer.errors.any? %>
        <div class="error_messages">
          <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this article from being saved:</h2>
          <ul>
          <% @answer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :text %><br />
        <%= f.text_field :text %>
      </div>

      <div class="actions"><%= f.submit %></div>
    <% end %>

    <div><!-- end of col-6 -->
  <div class="col-md-3"></div>
</div><!-- end of row -->

app/views/answers/show.html.erb
<h4><%= @answer.text %></h4>

<p>
  <%= link_to "Edit", edit_question_answer_path(@question,@answer) %> |
  <%= link_to "Delete Answer", question_answer_path(@question,@answer),
            :data => {:confirm => "Are you sure?", :method => "delete"} %> |
  <%= link_to "Browse Questions", questions_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header pull-left">
      <a class="navbar-brand" href="/">
      STACK NO-FLOW
      </a>
      </div>
      <div class="navbar-header navbar-right">
      <% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>
		</div>

  </div>
</nav>
<div class="container">
  <%= yield %>

  <div class="footer navbar-fixed-bottom">
  	<p>STACK NO-FLOW copyright © 2015</p>
  </div>
</div>
</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-3"></div>
    <div class="col-md-6 center-all-quests">
    <h3>All Questions</h3>

    <div id="questions-all">
    <% @questions.each do |question| %>
      <h2>
        <%= link_to question.title, question_path(question) %>
      </h2>
      <div class="info">
        by <%= question.user.name %>
        on <%= question.created_at.strftime('%b %d, %Y') %>
      </div>
      <div class="content"><%= question.content %></div>
    <% end %>
    </div>

    <% if current_user %>
      <button class="ask-btn"><%= link_to "See All Users", users_path %></button>
      <button class="ask-btn"><%= link_to "Ask a Question", new_question_path %></button>
    <% else %>
      <p>You must be signed in to ask a question</p>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/questions/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
    <div class="col-md-6 center-form">
      <h4>Ask your question: Insert a topic title and the question content!</h4>
    <%= form_for @question do |f| %>
      <% if @question.errors.any? %>
        <div class="error_messages">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this article from being saved:</h2>
          <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :content %><br />
        <%= f.text_field :content %>
      </div>
      <div class="actions"><%= f.submit %></div>
    <% end %>

    <div><!-- end of col-6 -->
  <div class="col-md-3"></div>
</div><!-- end of row -->

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-3"></div>
    <div class="col-md-6 center-quest">

<h1 class="single-question-header"><%= @question.title %></h1>
<h3><%= @question.content %></h3>
<p>
  <%= link_to "Edit", edit_question_path(@question) %> |
  <%= link_to "Delete Question", question_path(@question),
            :data => {:confirm => "Are you sure?", :method => "delete"} %> |
  <%= link_to "Browse Questions", questions_path %>
</p>


 <% if @question.answers.any? %>
        <h4 class="sub-title">Answers:</h4>

        <div class="project-list">
          <% @question.answers.each do |answer| %>
            <div class="answer-items content">
              <span>Answered by: <%= answer.user.name %></span>
              <%= link_to answer.text, question_answer_path(@question, answer)%>

            </div>
          <% end %>
        </ul>
      <% else %>
        <p>There are no answers yet!</p>
      <% end %>
      <div class="b-group">
        <p><%= link_to "Add an Answer", new_question_answer_path(@question) %></p>
        <p><%= link_to "Return to Questions", questions_path %></p>
      </div>
      <div class="col-md-3"></div>
    </div><!-- end col-6 -->
</div><!-- end row -->

app/views/users/new.html.erb
<h1>New User Signup</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</div>
<div class="actions"><%= f.submit "Sign Up Now" %></div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3"></div>
    <div class="col-md-6 center-all-quests">
    <h3>All Users</h3>

    <div id="questions-all">
    <% @users.each do |user| %>
      <h2>
        <%= link_to user.name, user_path(user) %>
      </h2>
      <div class="info">
        <p><strong>is admin?</strong> <%= user.admin %></p>
        <p><strong>joined on </strong> <%= user.created_at.strftime('%b %d, %Y') %></p>

        <p><strong>ALL Questions this User Asked:</strong></p>
        <% user.questions.each do |question| %>
        <p><%= question.title %></p>
        <% end %>
        <p><strong>All Answers from this User:</strong></p>
        <% user.answers.each do |answer| %>
        <p><%= answer.text %></p>
        <% end %>
      </div>

    <% end %>
    </div>

    <% if current_user %>

      <button class="ask-btn"><%= link_to "Edit User", new_question_path %></button>
    <% else %>
      <p>You must be signed in to ask a question</p>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>